name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', macos-12]
        python-version: ['3.11']
        include:
          - os: 'ubuntu-22.04'
            executable_extension: -linux
          - os: macos-12
            executable_extension: -macos

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile adr/adr.py

    - name: Tar up executable and announch filename
      run: |
        ASSET_NAME=adr${{ matrix.os }}.tar.gz
        cd dist
        tar -czvf $ASSET_NAME adr
        echo "ASSET_NAME=$ASSET_NAME" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/${{ env.ASSET_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
